# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - task: Npm@1
    displayName: 'npm install angular cli'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install @angular/cli -g'

  - task: Npm@1
    displayName: 'npm install packages'
    inputs:
      verbose: false

  - script: 'npm run build:ssr'
    displayName: 'build the project'

  - task: CopyFiles@2
    inputs:
      Contents: "dist/**" # Pull the build directory (React)
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: CopyFiles@2
    displayName: "Copy main.js to the root"
    inputs:
      SourceFolder: "dist/noozter-web/server"
      Contents: "main.js"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: DeleteFiles@1
    displayName: "Delete the server's dist/main.js"
    inputs:
      SourceFolder: "$(Build.ArtifactStagingDirectory)/dist/noozter-web/server"
      Contents: main.js

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory) # dist or build files
      ArtifactName: "www" # output artifact named www
